esphome:
  name: doorbellsensor
  platform: ESP8266
  #board: esp01_1m
  board: d1_mini

#Notes: to upload this to the esp, use the following commands: 
# cd C:\Users\msn\Documents\python\rftoy
# .\Scripts\activate
# esphome wemosd1_doorbell_sensor.yaml run
#

wifi:
  ssid: !secret wifi_untrust_ssid
  password: !secret wifi_untrust_password
  domain: !secret wifi_domain
  #power_save_mode: none
  #manual_ip:
  #  # Set this to the IP of the ESP
  #  static_ip: 192.168.2.229
  #  # Set this to the IP address of the router. Often ends with .1
  #  gateway: 192.168.2.1
  #  # The subnet of the network. 255.255.255.0 works for most home networks.
  #  subnet: 255.255.255.0

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: !secret fallback_ap_ssid
    password: !secret fallback_ap_password

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: !secret ha_api_password
  reboot_timeout: 0s

ota:
  password: !secret ota_password
  
remote_receiver:
  pin: 
    number: GPIO5  #GPIO5= D1
    #number: GPIO14  #GPIO14 = D5
    #inverted: True
  #dump: all
  dump: rc_switch
  #filter: 150us
  #idle: 10ms
  # Settings to optimize recognition of RF devices
  tolerance: 60%
  filter: 4us
  idle: 4ms
  buffer_size: 2kb
  # Settings to optimize recognition of RF devices
  #tolerance: 50%
  #filter: 10us
  #idle: 6ms
  #buffer_size: 2kb
  

# Individual outputs
binary_sensor:
  - platform: remote_receiver
    name: "Doorbell"
    rc_switch_raw:
      code: '110111110001110111001000'
      # code: '110111110001110111' -- doesn't work
      protocol: 7
    filters:
      delayed_off: 500ms
      
remote_transmitter:
  pin: GPIO4 # GPIO4  = D2
  # RF uses a 100% carrier signal
  carrier_duty_percent: 100%

switch:
  - platform: template
    name: "Bedroom Light On"
    id: bedroom_light_on
    turn_on_action:
      - remote_transmitter.transmit_rc_switch_raw:
          code: '00110111111000000001100000001010'
          protocol: 1
  #- platform: template
  #  name: "Bedroom Light Off"
  #  id: bedroom_light_off
    turn_off_action:
      - remote_transmitter.transmit_rc_switch_raw:
          code: '00110111111000000001000000001010'
          protocol: 1
  # Switch to restart the doorbell.
  - platform: restart
    name: Doorbell Restart
  - platform: template
    name: Trigger Doorbell
    turn_on_action:
      - remote_transmitter.transmit_rc_switch_raw:
          code: '110111110001110111001000'
          protocol: 7


# Enable the i2c bus, no additional configuration is required as ESPHome can auto-detect config
#i2c:

#From Chris

# Enable Web server.
web_server:
  port: 80
  auth:
    username: !secret web_username
    password: !secret web_password

# Sync time with Home Assistant.
time:
  - platform: homeassistant
    id: ha_time

#font:
#  - file: "arial.ttf"
#    id: my_font
#    size: 10

#display:
#  - platform: ssd1306_i2c
#    model: "SSD1306 128x64"
#    lambda: |-
#      //Print the string "Hello World!" at [0,10]
#      it.strftime(0, 0, id(my_font), "%Y-%m-%d %H:%M", id(ha_time).now());
#      //Then print whatever I tell you to
#      //it.printf(0, 14, id(my_font), "%s", id(rftoy3_text).state.c_str());
#      it.printf(0, 14, id(my_font), "%s", "rftoy3matt.yaml");
#      //Then print whatever I tell you to
#      //it.strftime(0, 21, id(my_font), "%H:%M:%S", id(sensor_uptime));
    
text_sensor:
  #- platform: homeassistant
  #  entity_id: input_text.rftoy3_text
  #  name: "RFToy Text"
  #  id: rftoy3_text
  ## Expose ESPHome version as sensor.
  - platform: version
    name: Doorbell ESPHome Version
  # Expose WiFi information as sensors.
  - platform: wifi_info
    ip_address:
      name: Doorbell IP
    ssid:
      name: Doorbell SSID

# Sensors with general information.
sensor:
  # Uptime sensor.
  - platform: uptime
    name: Doorbell Uptime
    id: sensor_uptime

  # WiFi Signal sensor.
  - platform: wifi_signal
    name: Doorbell WiFi Signal
    update_interval: 60s
  
#Temperature and Humidity Sensor
#  - platform: dht
#    pin: D1 #GPIO5
#    #model: DHT22
#    model: AM2302
#    temperature:
 #     name: "Doorbell Temperature"
 #   humidity:
 #     name: "Doorbell Humidity"
 #   update_interval: 60s

# Example configuration entry
#uart:
#  rx_pin: GPIO12
#  baud_rate: 9600