substitutions:
  location_name: "Kitchen"
  device_name: kitchen-weather-sensor
  friendly_name: "Kitchen Weather Sensor"
  device_ip: 192.168.2.244

#################################


# Help from: https://esphome.io/components/sensor/bme280.html
esphome:
  name: ${device_name}
  platform: ESP8266
  board: esp01_1m
  esp8266_restore_from_flash: true

wifi:
  ssid: !secret wifi_untrust_ssid
  password: !secret wifi_untrust_password
  domain: !secret wifi_domain
  #manual_ip:
  #  static_ip: ${device_ip}
  #  gateway: 192.168.2.1
  #  subnet: 255.255.255.0
  

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: !secret fallback_ap_ssid
    password: !secret fallback_ap_password

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: !secret ha_api_password

ota:
  password: !secret ota_password

# The web_server & sensor components can be removed without affecting core functionaility.
web_server:
  port: 80
  auth:
    username: !secret web_username
    password: !secret web_password

i2c:

sensor:
  - platform: wifi_signal
    name: ${device_name} Wifi Signal Strength
    update_interval: 60s
  - platform: uptime
    name: ${device_name} Uptime
  - platform: bme280
    temperature:
      name: ${location_name} Temperature
      oversampling: 16x
    pressure:
      name: ${location_name} Pressure
      oversampling: 16x
    humidity:
      name: ${location_name} Humidity
      oversampling: 16x
    address: 0x76
    update_interval: 60s

#################################

status_led:
  pin:
    number: GPIO0
    inverted: True

switch:
  - platform: restart
    name: "${friendly_name} REBOOT"
    
    
# Sync time with Home Assistant.
time:
  - platform: homeassistant
    id: ha_time